using System.Collections.Generic;
using NewPlayerHunter.Domain;

namespace NewPlayerHunter.Gameplay
{
    internal static class SixWeekContentFactory
    {
        public static List<PlayerContentEntry> BuildPlayers()
        {
            return new List<PlayerContentEntry>
            {
                Player("player.rocket.rory", 0, 1, 3, L("罗里·奎克", "Rory Quick"), PlayerPosition.Forward, 88, 86, 76, 900, 1400,
                    L("2023–2025 河谷联青训；2025–2026 连续租借至两支名字相近的俱乐部，进球归属仍在核对。",
                        "2023–2025 River Valley United academy; 2025–2026 consecutive loans to two clubs with confusingly similar names — goal attribution still being verified."),
                    L("擅长反越位的冲刺型前锋。经纪人坚持只在下坡路段测试他的速度。",
                        "A sprinting striker who specializes in beating the offside trap. His agent insists on timing his speed only on downhill stretches."),
                    L("经纪公司宣称他上赛季攻入 41 球。",
                        "His agency claims he scored 41 goals last season."),
                    L("能找到的两场完整录像都证明跑位聪明，但没人找到那 41 个进球所在的联赛积分榜。",
                        "The two full match recordings available prove his movement is clever, but nobody has found the league table containing those 41 goals."),
                    EvidenceReliability.Medium,
                    L("罗里不等了：已与山区速降队签约",
                        "Rory stopped waiting: signed with a mountain downhill team"),
                    L("罗里的经纪人表示，足球俱乐部迟迟没有报价，他决定接受一支山区球队的邀请。对方唯一承诺是主场确实有坡。",
                        "Rory's agent says that with no offer forthcoming from football clubs, he has accepted an invitation from a mountain team. Their only promise is that the home ground really does have a slope.")),
                Player("player.metronome.milo", 1, 2, 6, L("米洛·陈", "Milo Chen"), PlayerPosition.Midfielder, 81, 82, 91, 800, 1100,
                    L("2021–2026 港口竞技中场，连续五个赛季出场率全队前三，采访字数全队倒数第一。",
                        "2021–2026 Harbour Athletic midfielder; top three in the squad for appearances five seasons running, dead last in the squad for interview word count."),
                    L("位置感出色的组织型中场，踢球安静，采访更安静。",
                        "A deep-lying playmaker with an excellent sense of position. Quiet on the pitch; even quieter in interviews."),
                    L("前教练称他为“不会上热搜的发动机”。",
                        "A former coach called him 'the engine that never trends'."),
                    L("三场完整比赛里，他始终能为持球队友提供接应，并让阵型保持在同一张战术板上。",
                        "Across three full matches he consistently offered a passing option to the ball carrier and kept the shape on the same tactics board."),
                    EvidenceReliability.High,
                    L("米洛接受了数据分析师岗位",
                        "Milo has accepted a data analyst position"),
                    L("米洛等了六周仍没有正式安排，于是加入俱乐部分析部门。他说至少电子表格会按时回传球。",
                        "After six weeks without a formal placement, Milo joined a club's analytics department. He says at least spreadsheets pass the ball back on time.")),
                Player("player.wall.walter", 2, 3, 4, L("沃尔特·科瓦奇", "Walter Kovacs"), PlayerPosition.Defender, 85, 73, 84, 750, 1000,
                    L("2019–2026 北方铸造队中后卫，三次入选周最佳阵容，一次入选月度最佳撞墙。",
                        "2019–2026 Northern Foundry centre-back; three Team of the Week selections, one Collision of the Month."),
                    L("强壮的中后卫，转身速度一般，但正面对抗很少吃亏。",
                        "A powerful centre-back. Turning pace is ordinary, but he rarely loses a head-on duel."),
                    L("他的表哥声称，同一个人从来不可能第二次过掉他。",
                        "His cousin claims no opponent has ever dribbled past him twice."),
                    L("录像证实第一下对抗很硬；偶尔也会因为追球太执着，跑出整条防线的邮政编码。",
                        "Footage confirms the first challenge is bone-hard; occasionally he chases the ball so obsessively he leaves the defensive line's postcode."),
                    EvidenceReliability.Medium,
                    L("沃尔特回老家接管家具店",
                        "Walter heads home to take over the furniture store"),
                    L("沃尔特没有等到合适合同，决定回家经营衣柜生意。经纪人强调，这与球探报告中频繁出现“像衣柜一样结实”毫无关系。",
                        "With no suitable contract arriving, Walter decided to go home and run the wardrobe business. His agent stresses this has absolutely nothing to do with scout reports repeatedly describing him as 'solid as a wardrobe'.")),
                Player("player.turbo.tess", 3, 2, 5, L("泰丝·奥科罗", "Tess Okoro"), PlayerPosition.Winger, 77, 94, 67, 650, 950,
                    L("2022–2026 海岸青年队边锋，保持队史最快 60 米纪录，传中落点纪录不予公开。",
                        "2022–2026 Coast Youth winger; holds the club-record fastest 60 metres. The cross-placement records are not being made public."),
                    L("爆发力突出的边锋，启动很快，最后一传还在学习减速。",
                        "An explosive winger with a lightning first step; her final ball is still learning to slow down."),
                    L("青训中心称她的第一步“任何边后卫都拦不住”。",
                        "The academy says her first step is 'unstoppable for any full-back'."),
                    L("速度确实突出；传中质量不稳定，有时球会比禁区里的队友早到下一块广告牌。",
                        "The pace is genuinely elite; the crossing is erratic — sometimes the ball reaches the next advertising hoarding before her teammates reach the box."),
                    EvidenceReliability.High,
                    L("泰丝转投室内五人制联赛",
                        "Tess moves to an indoor futsal league"),
                    L("泰丝接受了五人制球队的合同。她说场地更小，至少传中飞出边线后不会消失太久。",
                        "Tess accepted a futsal contract. She says the pitch is smaller, so at least a cross that flies out of play won't be gone for long.")),
                Player("player.gloves.gus", 4, 4, 3, L("格斯·贝克", "Gus Baker"), PlayerPosition.Goalkeeper, 79, 78, 88, 600, 850,
                    L("2020–2026 市政体育场梯队门将，扑点训练营常驻示范，公交车月票连续六年全勤。",
                        "2020–2026 Municipal Stadium youth goalkeeper; permanent demonstrator at penalty-saving camps; six consecutive years of perfect attendance on his bus pass."),
                    L("处理高球稳健的门将，训练态度认真，偶尔会对公交车时刻表失误。",
                        "A goalkeeper who deals with high balls reliably and trains hard, though he occasionally fumbles the bus timetable."),
                    L("他声称曾在一个下午扑出五粒点球。",
                        "He claims he saved five penalties in a single afternoon."),
                    L("官方记录是四次扑救；第五名罚球手在助跑前请了病假。",
                        "The official record says four saves; the fifth taker called in sick before his run-up."),
                    EvidenceReliability.High,
                    L("格斯加入点球训练营担任教练",
                        "Gus joins a penalty camp as a coach"),
                    L("格斯没有收到职业合同，转而教授青少年门将扑点球。招生海报仍写着“五连扑”，第五名学员目前也请了病假。",
                        "With no professional contract, Gus turned to teaching young keepers penalty saves. The enrolment poster still says 'five saves in a row'; the fifth student has currently also called in sick.")),
                Player("player.showboat.sonny", 5, 5, 2, L("桑尼·布莱兹", "Sonny Blaze"), PlayerPosition.Forward, 63, 69, 34, 500, 1200,
                    L("2023–2026 多支短约球队前锋，集锦总时长 47 分钟，完整出场总时长略少于集锦。",
                        "2023–2026 striker for various short-contract clubs; career highlight reel runs 47 minutes, marginally longer than his total minutes of full appearances."),
                    L("脚下花样很多的前锋，个人集锦比完整比赛录像长。",
                        "A striker with endless tricks; his personal highlight reel is longer than his full-match footage."),
                    L("他的团队把每次穿裆都称为一次战术革命。",
                        "His team describes every nutmeg as a tactical revolution."),
                    L("地方媒体认可他的灵感，同时记录了多次迟到，以及一次错过球队大巴后责怪导航软件。",
                        "Local media acknowledge his flair, while also logging repeated late arrivals — including one missed team bus that he blamed on the navigation app."),
                    EvidenceReliability.Medium,
                    L("桑尼签约短视频平台",
                        "Sonny signs with a short-video platform"),
                    L("桑尼表示传统足球无法完整容纳他的创意，已转型为全职技巧主播。首期节目是《如何在不回防的情况下保持镜头感》。",
                        "Sonny says traditional football cannot fully contain his creativity and has become a full-time skills streamer. Episode one: 'How to Stay Camera-Ready Without Tracking Back'.")),
                Player("player.utility.uma", 6, 3, 7, L("乌玛·费尔南德斯", "Uma Fernandez"), PlayerPosition.WingBack, 75, 87, 86, 550, 750,
                    L("2021–2026 两支乙级球队翼卫，左右两侧出场次数几乎完全相等，统计员因此获奖。",
                        "2021–2026 wing-back for two second-division clubs; appearances on the left and right flanks almost exactly equal — the statistician won an award for it."),
                    L("能踢左右两侧的翼卫，跑动积极，对临时改阵适应很快。",
                        "A wing-back comfortable on either flank, an energetic runner who adapts instantly to mid-match formation changes."),
                    L("两家旧俱乐部都推荐她的适应能力。",
                        "Both former clubs recommend her adaptability."),
                    L("独立比赛记录显示，她在两侧都能稳定回追、套边和接应，推荐内容可信度较高。",
                        "Independent match records show she recovers, overlaps and supports reliably on both flanks; the recommendations check out."),
                    EvidenceReliability.High,
                    L("乌玛加入救火教练组",
                        "Uma joins a firefighting coaching staff"),
                    L("长期没有球队给出球员合同后，乌玛接受了青年队助教职位。她现在负责示范所有位置，除了财务主管。",
                        "After a long wait without a playing contract, Uma accepted a youth-team assistant role. She now demonstrates every position except treasurer.")),
                Player("player.cousin.carlo", 7, 1, 2, L("卡洛·贝利尼", "Carlo Bellini"), PlayerPosition.Midfielder, 42, 58, 51, 200, 350,
                    L("2024–2026 雨城竞技青年队中场，训练出席率良好（恩佐叔叔代为签到）。",
                        "2024–2026 Rainy City Athletic youth midfielder; training attendance excellent (Uncle Enzo signs in on his behalf)."),
                    L("比赛样本极少的中场，简历由亲属转交，并附带一顿规格过高的午餐。",
                        "A midfielder with a vanishingly small match sample. His résumé was hand-delivered by a relative and came with a suspiciously lavish lunch."),
                    L("家人坚称他能提前三步读懂比赛。",
                        "His family insist he reads the game three moves ahead."),
                    L("近期唯一可查证的材料是一张替补席旁的照片，球衣号码被三明治挡住。",
                        "The only recent verifiable material is a photo beside the substitutes' bench, his shirt number obscured by a sandwich."),
                    EvidenceReliability.Low,
                    L("卡洛改行经营高级三明治店",
                        "Carlo switches careers to run a gourmet sandwich shop"),
                    L("恩佐叔叔来信说卡洛决定尊重自己的真正天赋：把任何会议变成午餐。新店开业，包厢仍叫“中场控制区”。",
                        "Uncle Enzo writes that Carlo has decided to honour his true gift: turning any meeting into lunch. The new shop is open; the private room is still called the 'Midfield Control Zone'.")),
                Player("player.zodiac.luna", 8, 3, 2, L("露娜·萨维奇", "Luna Savage"), PlayerPosition.Winger, 74, 81, 59, 450, 700,
                    L("2022–2026 星光女足边锋（租借两次），满月夜比赛 11 场不败，其余夜晚战绩另询。",
                        "2022–2026 Starlight Women winger (two loan spells); unbeaten in 11 matches on full-moon nights — records for other nights available on request."),
                    L("习惯内切的左边锋，做定位球决定前会查看星象应用。",
                        "A left winger who loves cutting inside, and who checks her astrology app before any set-piece decision."),
                    L("经纪人说她在满月夜从不丢失球权。",
                        "Her agent says she never loses possession on full-moon nights."),
                    L("白天比赛同样能看到不错的内切能力；定位球选择则与天气、月相和手机电量同时相关。",
                        "Daytime matches show the same tidy cutting inside; her set-piece choices correlate simultaneously with weather, moon phase and phone battery."),
                    EvidenceReliability.Medium,
                    L("露娜暂停足球，等待水星顺行",
                        "Luna pauses football until Mercury goes direct"),
                    L("露娜认为本月合同谈判窗口与行星运行方向冲突，决定暂时休息。经纪人拒绝给出回归日期，只发来一张星盘。",
                        "Luna believes this month's contract-negotiation window conflicts with planetary motion and has decided to rest. Her agent declined to give a return date and sent only a birth chart.")),
                Player("player.forms.felix", 9, 4, 5, L("费利克斯·文书", "Felix Files"), PlayerPosition.Goalkeeper, 68, 72, 94, 450, 600,
                    L("2018–2026 注册处体育场守门员，八年零漏表，扑救流程合规率 100%。",
                        "2018–2026 Registry Stadium goalkeeper; eight years without a missed form; 100% procedural compliance on saves."),
                    L("基本功可靠的门将，做任何出击前都希望流程完整。",
                        "A fundamentally sound goalkeeper who likes the paperwork complete before any rush off his line."),
                    L("他声称职业生涯从未漏交过一张出击申请表。",
                        "He claims he has never once failed to file a sweep-up application form in his career."),
                    L("扑救动作稳定，职业态度很好；快速反击偶尔会被他的三联单拖慢。",
                        "Solid shot-stopping, impeccable professionalism; the occasional counter-attack gets delayed by his triplicate forms."),
                    EvidenceReliability.High,
                    L("费利克斯通过公务员考试",
                        "Felix passes the civil service exam"),
                    L("费利克斯接受了足协注册处职位。他说这里每一次盖章都算成功出击，而且不会有人突然起高球。",
                        "Felix accepted a post at the FA registration office. He says every stamp counts as a successful claim off the line, and nobody suddenly lumps a high ball at you.")),
                Player("player.rivet.rita", 10, 5, 6, L("丽塔·哈达德", "Rita Haddad"), PlayerPosition.Defender, 82, 78, 92, 800, 1100,
                    L("2019–2026 铁桥队队长级中卫，七次全队赛季最佳，消防演练特邀指导。",
                        "2019–2026 Ironbridge captain-grade centre-back; seven-time club Player of the Season; invited instructor at fire drills."),
                    L("位置感稳定的中后卫，处理危险球简单直接。",
                        "A positionally dependable centre-back who deals with danger simply and directly."),
                    L("旧队长说她能让禁区通过安全检查。",
                        "Her old captain says she can get a penalty area through a safety inspection."),
                    L("多场录像显示她很少为了镜头贸然上抢，解围路线也比很多俱乐部的消防通道清楚。",
                        "Extensive footage shows she rarely dives in for the cameras, and her clearance lanes are clearer than most clubs' fire exits."),
                    EvidenceReliability.High,
                    L("丽塔接受海外联赛报价",
                        "Rita accepts an offer from abroad"),
                    L("丽塔与另一家俱乐部完成签约。对方体育主管只问了两个问题：能不能防守，以及能不能让其他人也认真防守。",
                        "Rita completed a move to another club. Their sporting director asked only two questions: can she defend, and can she make everyone else defend properly too.")),
                Player("player.throwin.dino", 11, 4, 2, L("迪诺·马尔凯蒂", "Dino Marchetti"), PlayerPosition.Defender, 70, 83, 48, 400, 600,
                    L("2021–2026 河岸队边后卫，界外球均距联盟第一，停车场寻球次数也是第一。",
                        "2021–2026 Riverside full-back; league-best average throw-in distance; also league-best in balls retrieved from the car park."),
                    L("拥有超远距离界外球的边后卫，落点控制比较随缘。",
                        "A full-back with an enormous long throw; placement is left to fate."),
                    L("他把每次界外球都称为一次重新发明定位球。",
                        "He calls every throw-in a reinvention of the set piece."),
                    L("投掷距离确实惊人；两次训练因为皮球飞出场馆，需要工作人员去停车场寻找。",
                        "The distance is genuinely astonishing; two training sessions were interrupted while staff searched the car park for the ball."),
                    EvidenceReliability.Medium,
                    L("迪诺加入标枪俱乐部",
                        "Dino joins a javelin club"),
                    L("迪诺认为足球对手臂天赋缺乏尊重，已加入当地田径队。第一堂课的重点是学习不要把标枪扔向角旗区。",
                        "Dino believes football fails to respect arm talent and has joined the local athletics team. Lesson one: learning not to hurl the javelin toward the corner flag.")),
                Player("player.spreadsheet.nova", 12, 5, 8, L("诺瓦·伊万诺娃", "Nova Ivanova"), PlayerPosition.Midfielder, 84, 76, 89, 750, 1050,
                    L("2020–2026 大学联赛中场后转入职业队，传球成功率 87%，早餐计划执行率未知。",
                        "2020–2026 university-league midfielder turned pro; 87% pass completion; breakfast-plan adherence unknown."),
                    L("擅长在高压下向前传球的中场，也热衷赛前数据准备。",
                        "A midfielder who plays forward under pressure, and who loves pre-match data preparation."),
                    L("她说自己能用三列公式找出传球线路。",
                        "She says she can find a passing lane with three columns of formulas."),
                    L("完整比赛证明她不仅会做表格，也敢在逼抢下处理球；队友只是不喜欢收到带筛选器的早餐计划。",
                        "Full matches prove she's more than a spreadsheet — she'll play through a press. Teammates merely object to breakfast plans that arrive with filter dropdowns."),
                    EvidenceReliability.High,
                    L("诺瓦加入冠军联赛数据部门",
                        "Nova joins a Champions League data department"),
                    L("诺瓦接受了一家洲际赛事数据供应商的职位。她留下最后一句话：至少数据库不会在第八十分钟突然改踢四前锋。",
                        "Nova accepted a role with a continental competition's data provider. Her parting line: at least a database doesn't suddenly switch to four up front in the eightieth minute.")),
                Player("player.bothfeet.echo", 13, 6, 8, L("艾可·摩根", "Echo Morgan"), PlayerPosition.WingBack, 80, 90, 77, 700, 950,
                    L("2021–2026 东西两翼均有完整赛季，左右脚进球差为 0，鞋柜分配仍未裁决。",
                        "2021–2026 full seasons on both the east and west flanks; goal difference between left and right foot is 0; boot-cupboard allocation still under arbitration."),
                    L("左右脚均衡、能覆盖两条边路的翼卫。",
                        "A truly two-footed wing-back who can cover either flank."),
                    L("经纪材料称她是“两名球员共用一双球鞋”。",
                        "Agent material describes her as 'two players sharing one pair of boots'."),
                    L("左右两侧样本都很稳定，唯一争论是更衣室究竟该给她左边还是右边的柜子。",
                        "Samples from both flanks are equally solid; the only debate is whether her dressing-room locker should be on the left or the right."),
                    EvidenceReliability.High,
                    L("艾可加盟竞争对手",
                        "Echo signs for a rival"),
                    L("艾可没有继续等待，已与另一家俱乐部签约。发布会上她分别用左右脚颠球，公关部因此发了两份新闻稿。",
                        "Echo stopped waiting and signed for another club. At the unveiling she juggled with her left foot and her right, so the PR department issued two press releases.")),
                Player("player.thermos.vic", 14, 2, 3, L("维克·哈珀", "Vic Harper"), PlayerPosition.Forward, 78, 60, 95, 300, 500,
                    L("2008–2026 六家俱乐部禁区前锋，六码区进球 91 个，保温杯续约四次。",
                        "2008–2026 penalty-box striker at six clubs; 91 goals from inside the six-yard box; the thermos has been renewed four times."),
                    L("经验丰富的禁区前锋，冲刺不多，但对落点判断很好，随身带保温杯。",
                        "A veteran box striker. Sprints are rare, but his reading of where the ball will drop is superb. Carries a thermos everywhere."),
                    L("他坚持速度会消失，但六码区不会搬家。",
                        "He insists pace fades, but the six-yard box never moves house."),
                    L("近年冲刺次数下降明显；六码区触球选择和职业态度仍然可靠。",
                        "Sprint counts have dropped sharply in recent years; his touch selection in the six-yard box and his professionalism remain impeccable."),
                    EvidenceReliability.High,
                    L("维克宣布退役",
                        "Vic announces his retirement"),
                    L("维克决定结束球员生涯。他说膝盖已经投票通过，保温杯以全票当选下一任经纪人。",
                        "Vic has decided to end his playing career. He says his knees have voted it through, and the thermos was elected his next agent unanimously.")),
                Player("player.academy.perry", 15, 1, 5, L("佩里·金", "Perry King"), PlayerPosition.Forward, 67, 91, 43, 250, 450,
                    L("2023–2026 青训营前锋，青年队金靴一次，成年队出场 0 分钟，纪录片两季。",
                        "2023–2026 academy striker; one youth Golden Boot, 0 senior minutes, two seasons of documentary."),
                    L("速度出色的青年前锋，成年比赛为零，个人纪录片已经拍到第二季。",
                        "A rapid young striker with zero senior appearances and a personal documentary already in its second season."),
                    L("团队称他为“无法被定义的九号半”。",
                        "His team calls him 'the undefinable nine-and-a-half'."),
                    L("青年比赛能看到速度和射门潜力；成年对抗、决策和准时性仍未得到验证。",
                        "Youth matches show pace and finishing promise; senior physicality, decision-making and punctuality remain unverified."),
                    EvidenceReliability.Medium,
                    L("佩里进入真人秀封闭拍摄",
                        "Perry enters closed reality-show filming"),
                    L("佩里的团队暂停所有试训，因为纪录片平台要求剧情保密。经纪人承诺下一季会出现“至少一次真正的成年比赛”。",
                        "Perry's team has suspended all trials because the documentary platform demands plot secrecy. His agent promises next season will feature 'at least one real senior match'."))
            };
        }

        public static List<DemandContentEntry> BuildDemands()
        {
            return new List<DemandContentEntry>
            {
                Demand("demand.week1.emergency", "club.rainy", L("雨城竞技", "Rainy City Athletic"),
                    L("上赛季联赛第 4 名，目前参加洲际冠军联赛资格赛",
                        "Finished 4th in the league last season; currently in Continental Champions League qualifying"),
                    L("历史最佳：洲际冠军联赛四强（12 年前）",
                        "Best ever: Continental Champions League semi-finals (12 years ago)"),
                    L("预算充足、舆论压力巨大。董事会把“重返欧洲之巅”印在每一个咖啡杯上。",
                        "Deep pockets, enormous media pressure. The board has 'Back to the Summit of Europe' printed on every coffee mug."),
                    L("资格赛前锋告急",
                        "Urgent: striker needed for qualifiers"),
                    L("主力前锋在热身赛拉伤，俱乐部需要一名能立即参加合练、理解反越位并愿意积极逼抢的前锋。",
                        "The first-choice striker pulled a muscle in a friendly. The club needs a forward who can join full training immediately, understands beating the offside trap, and will press willingly."),
                    1, 2, 1200,
                    L("提交后 1–2 周反馈；通过试训后付款。",
                        "Feedback within 1–2 weeks of submission; payment after a successful trial."),
                    L("雨城竞技关闭紧急前锋招聘",
                        "Rainy City Athletic close emergency striker search"),
                    L("雨城竞技已从预备队提拔一名前锋。体育主管感谢所有推荐，并表示下次会在主力受伤前阅读体检报告。",
                        "Rainy City Athletic have promoted a striker from the reserves. The sporting director thanks all referrers and says next time he'll read the medical report before the starter gets injured."),
                    Slot("slot.week1.forward", PlayerPosition.Forward, 74, 68, 60)),
                Demand("demand.week2.group", "club.dockyard", L("船坞联", "Dockyard United"),
                    L("上赛季联赛第 11 名，本季目标进入上半区",
                        "Finished 11th last season; targeting a top-half finish this year"),
                    L("历史最佳：联赛亚军；最近一次发生在俱乐部仍用传真机的年代",
                        "Best ever: league runners-up — most recently back when the club still used the fax machine"),
                    L("中游俱乐部，青训和定位球出名，财务主管会认真核对每一杯训练饮料。",
                        "A mid-table club famous for its academy and set pieces. The finance officer personally audits every training-ground sports drink."),
                    L("前场与中场联合试训",
                        "Joint trial: forward and midfielder"),
                    L("球队需要一名前锋和一名能维持攻守距离的中场。允许部分推荐，但完整方案报酬更高。",
                        "The team needs a striker and a midfielder who can keep the distances between defence and attack. Partial referrals accepted, but a complete package pays better."),
                    2, 3, 2100,
                    L("按实际完成的槽位结算；结果延迟 1–2 周。",
                        "Paid per slot actually filled; results delayed 1–2 weeks."),
                    L("船坞联结束联合试训",
                        "Dockyard United end joint trial"),
                    L("船坞联从青训队补进两人，招聘提前结束。主教练称阵容已经足够完整，财务主管称餐费也终于完整。",
                        "Dockyard United promoted two academy players and closed recruitment early. The head coach says the squad is finally complete; the finance officer says the meal budget finally is too."),
                    Slot("slot.week2.forward", PlayerPosition.Forward, 70, 62, 58),
                    Slot("slot.week2.midfield", PlayerPosition.Midfielder, 72, 68, 70)),
                Demand("demand.week3.longterm", "club.oldcastle", L("旧堡王冠", "Oldcastle Crown FC"),
                    L("上赛季联赛第 2 名，连续六年参加洲际冠军联赛",
                        "Finished 2nd last season; six straight years in the Continental Champions League"),
                    L("历史最佳：3 次联赛冠军、1 次洲际冠军联赛决赛",
                        "Best ever: 3 league titles, 1 Continental Champions League final"),
                    L("传统豪门，球迷要求争冠，董事会每次换教练都称其为“长期规划的最后一块拼图”。",
                        "A traditional giant whose fans demand the title. Every coaching change is announced as 'the final piece of the long-term plan'."),
                    L("争冠阵容补强计划",
                        "Title-squad reinforcement plan"),
                    L("俱乐部需要一名能守大空间的中后卫，以及一名能在欧战低位防守前制造一对一优势的边锋。",
                        "The club needs a centre-back who can defend big spaces, and a winger who can create one-on-one advantages against deep European blocks."),
                    3, 3, 2800,
                    L("可部分完成；两个位置全部满足时支付完整顾问费。",
                        "Partial completion allowed; the full consultancy fee is paid when both positions are filled."),
                    L("旧堡王冠停止本轮补强",
                        "Oldcastle Crown FC halt this round of recruitment"),
                    L("董事会决定把预算留给冬季窗口，并发布了第九版长期规划。第八版仍然有效，只是不再被任何人提起。",
                        "The board decided to save the budget for the winter window and published the ninth edition of the long-term plan. The eighth edition remains in force; nobody mentions it anymore."),
                    Slot("slot.week3.defender", PlayerPosition.Defender, 78, 70, 76),
                    Slot("slot.week3.winger", PlayerPosition.Winger, 76, 80, 65)),
                Demand("demand.week4.keeper", "club.seaside", L("海港蓝鸥", "Harbour Bluegulls FC"),
                    L("上赛季联赛第 15 名，通过附加赛保级",
                        "Finished 15th last season; survived via the play-offs"),
                    L("历史最佳：国内杯赛四强",
                        "Best ever: domestic cup semi-finals"),
                    L("预算有限但主场风很大。俱乐部把所有传中失误统称为“海洋气候变量”。",
                        "Limited budget, very windy home ground. The club classifies all crossing errors as 'maritime climate variables'."),
                    L("保级队门将短期招聘",
                        "Relegation battler seeks short-term goalkeeper"),
                    L("一号门将肩部受伤，需要能处理高球、指挥防线并承受密集射门的门将。",
                        "The first-choice keeper has a shoulder injury. The club needs a goalkeeper who can deal with high balls, organise the defence, and withstand a barrage."),
                    4, 2, 1300,
                    L("通过体检和试训后结算，反馈延迟 1–2 周。",
                        "Settled after medical and trial; feedback delayed 1–2 weeks."),
                    L("海港蓝鸥撤回门将需求",
                        "Harbour Bluegulls FC withdraw goalkeeper request"),
                    L("一号门将恢复速度快于预期，俱乐部撤回招聘。队医表示这次没有参考潮汐表。",
                        "The first-choice keeper recovered faster than expected and the club withdrew the request. The club doctor confirms the tide tables were not consulted this time."),
                    Slot("slot.week4.keeper", PlayerPosition.Goalkeeper, 72, 68, 74)),
                Demand("demand.week5.group", "club.foundry", L("铁炉竞技", "Foundry Athletic"),
                    L("上赛季联赛第 7 名，正在争取洲际次级赛事资格",
                        "Finished 7th last season; chasing qualification for the continental second-tier competition"),
                    L("历史最佳：2 次国内杯赛冠军",
                        "Best ever: 2 domestic cup titles"),
                    L("强调纪律、对抗和二点球。主教练办公室只有两本书：《防守》与《继续防守》。",
                        "A club built on discipline, duels and second balls. The head coach's office holds exactly two books: Defending and More Defending."),
                    L("杯赛阵容双人补充",
                        "Cup squad: two additions needed"),
                    L("需要一名可靠中后卫和一名愿意参与前场压迫的前锋。个人摄制组必须留在训练基地外。",
                        "A dependable centre-back and a striker willing to join the high press. Personal camera crews must remain outside the training ground."),
                    5, 3, 2400,
                    L("允许部分提交；职业态度会明显影响最终报酬。",
                        "Partial submissions allowed; professionalism noticeably affects the final fee."),
                    L("铁炉竞技结束招聘",
                        "Foundry Athletic close recruitment"),
                    L("主教练从青年队提拔两名球员，并宣布他们已经学会最重要的战术：听见哨声就回防。",
                        "The head coach promoted two youth players and announced they have already mastered the most important tactic: when you hear the whistle, run back."),
                    Slot("slot.week5.defender", PlayerPosition.Defender, 76, 68, 78),
                    Slot("slot.week5.forward", PlayerPosition.Forward, 75, 72, 72)),
                Demand("demand.week6.future", "club.comets", L("彗星城", "Comet City FC"),
                    L("卫冕联赛冠军，本季洲际冠军联赛夺冠热门",
                        "Reigning league champions; favourites for this season's Continental Champions League"),
                    L("历史最佳：5 次联赛冠军、洲际冠军联赛四强",
                        "Best ever: 5 league titles, Continental Champions League semi-finals"),
                    L("数据部门规模与一支青年队相当。每次训练结束后，球员先恢复体能，再恢复账号密码。",
                        "The data department is the size of a youth squad. After every training session, players recover their legs first, then their account passwords."),
                    L("冠军阵容未来计划",
                        "Champions' squad future planning"),
                    L("寻找一名能在高压下组织进攻的中场，以及一名覆盖整条边路的翼卫，为联赛和洲际赛事双线轮换。",
                        "Seeking a midfielder who can build attacks under a high press, and a wing-back who covers the entire flank, for rotation across league and continental fixtures."),
                    6, 4, 3200,
                    L("两个位置全部满足时支付完整顾问费；反馈延迟 1–2 周。",
                        "Full consultancy fee paid when both positions are filled; feedback delayed 1–2 weeks."),
                    L("彗星城完成内部补强",
                        "Comet City FC strengthen from within"),
                    L("俱乐部决定启用两名青训球员。数据部门表示模型早已预测到这一结果，只是报告直到今天才完成渲染。",
                        "The club decided to promote two academy players. The data department says the model predicted this outcome long ago; the report only finished rendering today."),
                    Slot("slot.week6.midfield", PlayerPosition.Midfielder, 80, 72, 78),
                    Slot("slot.week6.wingback", PlayerPosition.WingBack, 76, 82, 74))
            };
        }

        public static List<MailContentEntry> BuildMails(
            IReadOnlyList<PlayerContentEntry> players,
            IReadOnlyList<DemandContentEntry> demands)
        {
            var mails = new List<MailContentEntry>
            {
                Mail("mail.w1.rainy", MailContentKind.ClubRequest, 1, L("雨城竞技 · 体育主管", "Rainy City Athletic · Sporting Director"), L("资格赛前锋告急：两周内完成推荐", "Urgent striker need: recommendations within two weeks"),
                    L("洲际冠军联赛资格赛临近，我们需要能立刻参加合练的前锋。",
                        "Continental Champions League qualifying is close; we need a striker who can join full training immediately."),
                    L("主力前锋在热身赛拉伤。球队希望候选人具备反越位意识、基本逼抢能力，并能承受资格赛主场四万名球迷同时叹气。俱乐部实力、截止日期和委托价见下方固定信息。",
                        "Our first-choice striker pulled a muscle in a friendly. Candidates should have a feel for beating the offside trap, basic pressing ability, and the resilience to survive forty thousand home fans sighing in unison. Club strength, deadline and fee are in the fixed details below."),
                    L("俱乐部正式招聘 · 第一手信息", "Official club recruitment · first-hand information"), demandId: "demand.week1.emergency"),
                Mail("mail.w1.rory", MailContentKind.PlayerResume, 1, L("极速经纪公司 · 巴里", "Top Speed Agency · Barry"), L("球员简历：罗里·奎克", "Player résumé: Rory Quick"),
                    L("冲刺能力突出；所谓 41 球仍缺少可核实的赛事记录。",
                        "Outstanding sprinter; the alleged 41 goals still lack verifiable competition records."),
                    L("罗里目前没有合同，可以立即参加试训。我们确认他的无球跑动和启动速度都很优秀。至于“上赛季 41 球”，统计人员正在寻找正确的联赛网页。",
                        "Rory is unattached and available for trial immediately. We confirm his off-ball runs and acceleration are excellent. As for 'the 41 goals last season', our statisticians are still looking for the correct league website."),
                    L("经纪人材料 · 宣传成分较高", "Agent material · heavy on promotion"), playerId: "player.rocket.rory"),
                Mail("mail.w1.perry", MailContentKind.PlayerResume, 1, L("王冠体育影业", "Crown Sports Pictures"), L("球员简历：佩里·金（成年比赛待补）", "Player résumé: Perry King (senior appearances pending)"),
                    L("青年队明星，速度和曝光度都很高，成年比赛样本为零。",
                        "Youth-team star; high marks for pace and exposure, zero senior-match sample."),
                    L("佩里希望进入一线队环境。他的纪录片已经拍到第二季，但成年比赛尚未开始。附件中有青年赛事集锦、品牌合作方案，以及一份长达十二页的进球庆祝计划。",
                        "Perry hopes to enter a first-team environment. His documentary is in its second season, though his senior career has yet to begin. Attached: youth-tournament highlights, a brand-partnership proposal, and a twelve-page goal-celebration plan."),
                    L("球员团队材料 · 品牌倾向明显", "Player's team material · strong brand lean"), playerId: "player.academy.perry"),
                Mail("mail.w1.carlo", MailContentKind.PrivateRequest, 1, L("恩佐叔叔", "Uncle Enzo"), L("帮卡洛进雨城竞技，午饭和谢礼都算我的", "Get Carlo into Rainy City Athletic — lunch and a thank-you gift on me"),
                    L("请托指定上赛季前四、参加洲际资格赛的雨城竞技。",
                        "The request specifies Rainy City Athletic: last season's top four, playing continental qualifiers."),
                    L("卡洛只是缺一次被豪门看见的机会。把他送进雨城竞技这次前锋招聘，位置不完全匹配也没关系。你会立即收到谢礼；球队以后若追问推荐依据，就说我们都相信他的潜力。",
                        "Carlo just needs one chance to be seen by a big club. Put him into Rainy City Athletic's striker recruitment — never mind that the position isn't a perfect match. You'll receive a thank-you gift immediately; if the club later asks what the recommendation was based on, just say we all believe in his potential."),
                    L("私人关系 · 明确利益冲突 · 证据不足", "Personal connection · clear conflict of interest · insufficient evidence"),
                    playerId: "player.cousin.carlo", offer: 350,
                    offerTerms: L("必须在本周把卡洛提交给雨城竞技；投给其他俱乐部不支付谢礼。",
                        "Carlo must be submitted to Rainy City Athletic this week; submissions to other clubs earn no thank-you gift."),
                    requiredClubId: "club.rainy",
                    targetClub: L("目标俱乐部：雨城竞技（上赛季第 4，参加洲际冠军联赛资格赛）",
                        "Target club: Rainy City Athletic (4th last season, in Continental Champions League qualifying)"),
                    risk: L("不匹配安排可能在后续调查中损害声望。",
                        "A mismatched placement may damage your reputation in any later investigation.")),
                Mail("mail.w1.office", MailContentKind.General, 1, L("球探事务所 · 系统通知", "Scouting Agency · System Notice"), L("新赛季工作说明：先看来源，再看报价", "New season briefing: check the source before the offer"),
                    L("游戏从季前训练开始，共 52 周；顶部日期会自动推进。",
                        "The game starts in pre-season and runs 52 weeks; the date at the top advances automatically."),
                    L("阅读招聘邮件后，对应需求才会进入分配页；阅读简历或私人请托后，球员才会进入可用名单。球员一旦提交给俱乐部就会离开可用名单，结果和款项通常延迟一至两周。",
                        "A demand only appears on the assignment page after you read the recruitment mail; a player only enters the available list after you read their résumé or a private request. Once submitted to a club, a player leaves the available list. Results and payments usually arrive one to two weeks later."),
                    L("系统规则 · 可直接信赖", "System rules · fully reliable")),

                Mail("mail.w2.dockyard", MailContentKind.ClubRequest, 2, L("船坞联 · 招聘办公室", "Dockyard United · Recruitment Office"), L("联合试训：前锋与中场各一名", "Joint trial: one forward, one midfielder"),
                    L("中游球队准备调整进攻结构，需求有效三周。",
                        "A mid-table side is restructuring its attack; the request stays open three weeks."),
                    L("我们需要一名能终结进攻的前锋，以及一名能让三条线保持联系的中场。可以只推荐其中一人，但如果两人互相不认识却能站在正确距离，主教练会非常感动。",
                        "We need a striker who finishes moves and a midfielder who keeps the three lines connected. You may recommend just one — but if two strangers can stand at exactly the right distances, the head coach will be deeply moved."),
                    L("俱乐部正式招聘 · 第一手信息", "Official club recruitment · first-hand information"), demandId: "demand.week2.group"),
                Mail("mail.w2.milo", MailContentKind.PlayerResume, 2, L("妮娅教练", "Coach Nia"), L("球员简历：米洛·陈", "Player résumé: Milo Chen"),
                    L("不抢镜的组织中场，能让身边队友踢得更舒服。",
                        "A selfless playmaker who makes everyone around him more comfortable."),
                    L("米洛擅长观察、接应和转移球。他最好的处理通常发生在进球前两脚，因此个人集锦很短，但完整比赛录像很好看。",
                        "Milo excels at scanning, supporting and switching play. His best work usually happens two touches before the goal, so his highlight reel is short — but his full-match footage is a pleasure."),
                    L("前教练推荐 · 可由完整比赛核实", "Former coach's recommendation · verifiable in full matches"), playerId: "player.metronome.milo"),
                Mail("mail.w2.vic", MailContentKind.PlayerResume, 2, L("老靴经纪社", "Old Boots Agency"), L("球员简历：维克·哈珀", "Player résumé: Vic Harper"),
                    L("经验丰富的禁区前锋，速度下降，但落点判断仍在。",
                        "Veteran box striker; the pace has faded, the reading of loose balls hasn't."),
                    L("维克不承诺赢下四十米冲刺，但知道大多数解围会落到哪里。他自带保温杯，也承诺不会占用俱乐部营养师的咖啡机。",
                        "Vic makes no promises over forty metres, but he knows where most clearances will drop. He brings his own thermos and promises not to occupy the club nutritionist's coffee machine."),
                    L("多年比赛记录 · 部分数据时效较旧", "Years of match records · some data somewhat dated"), playerId: "player.thermos.vic"),
                Mail("mail.w2.tess", MailContentKind.PlayerResume, 2, L("闪电青训中心", "Lightning Academy"), L("球员简历：泰丝·奥科罗", "Player résumé: Tess Okoro"),
                    L("边锋，速度优势明显，最后一传仍需打磨。",
                        "Winger; obvious pace advantage, final ball still needs polish."),
                    L("泰丝的第一步足以迫使边后卫提前转身。她已经准备好参加成年队试训；我们也建议训练基地把边线外的广告牌固定得更牢。",
                        "Tess's first step forces full-backs to turn early. She is ready for a senior trial; we also recommend the training ground bolt down the advertising boards beyond the touchline."),
                    L("青训报告 · 基本能力可核实", "Academy report · core abilities verifiable"), playerId: "player.turbo.tess"),
                Mail("mail.w2.window", MailContentKind.General, 2, L("联盟竞赛部", "League Competitions Department"), L("季前注册提醒：名单不是愿望清单", "Pre-season registration reminder: a squad list is not a wish list"),
                    L("夏季注册窗口即将进入繁忙阶段。",
                        "The summer registration window is about to get busy."),
                    L("各俱乐部必须在截止日前提交球员注册资料。联盟特别提醒：球员姓名、出生日期和实际存在的合同缺一不可；“董事长口头保证”仍不是文件类型。",
                        "All clubs must submit player registration documents before the deadline. The league would like to remind everyone: a player's name, date of birth and an actually existing contract are all indispensable; 'the chairman's verbal guarantee' is still not a document type."),
                    L("联盟公告 · 赛季时间信息", "League announcement · season calendar info")),

                Mail("mail.w3.oldcastle", MailContentKind.ClubRequest, 3, L("旧堡王冠 · 技术委员会", "Oldcastle Crown FC · Technical Committee"), L("争冠补强：中后卫与边锋", "Title push: centre-back and winger wanted"),
                    L("传统豪门为联赛和洲际赛事寻找轮换球员，需求有效三周。",
                        "A traditional giant seeks rotation players for league and continental campaigns; open three weeks."),
                    L("中后卫需要适应高位防线，边锋需要在阵地战中制造一对一优势。董事会保证这是长期规划，附件文件名也只写到了“最终版_第八次修改”。",
                        "The centre-back must suit a high line; the winger must create one-on-one advantages against set defences. The board guarantees this is a long-term plan — the attached file is only named 'FINAL_version_eighth_revision'."),
                    L("俱乐部正式招聘 · 第一手信息", "Official club recruitment · first-hand information"), demandId: "demand.week3.longterm"),
                Mail("mail.w3.walter", MailContentKind.PlayerResume, 3, L("北区球员代理", "North District Player Agency"), L("球员简历：沃尔特·科瓦奇", "Player résumé: Walter Kovacs"),
                    L("正面对抗强硬的中后卫，回追转身并非优势。",
                        "A centre-back ferocious in head-on duels; recovery runs and turning are not his strengths."),
                    L("沃尔特适合保护禁区和处理直接对抗。如果球队长期把四名后卫留在对方半场，他也会努力回追，只是摄影师可能需要广角镜头。",
                        "Walter is built to protect the box and win direct duels. If a team insists on leaving all four defenders in the opposition half, he will still try to get back — the photographer may just need a wide-angle lens."),
                    L("代理人材料 · 有完整比赛旁证", "Agent material · corroborated by full matches"), playerId: "player.wall.walter"),
                Mail("mail.w3.luna", MailContentKind.PlayerResume, 3, L("满月体育", "Full Moon Sports"), L("球员简历：露娜·萨维奇", "Player résumé: Luna Savage"),
                    L("能内切和处理定位球的左边锋，决策方式比较独特。",
                        "A left winger who cuts inside and takes set pieces; decision-making process is somewhat unique."),
                    L("露娜的技术和速度都达到职业试训水平。她偶尔会根据星象调整罚球顺序；经纪公司认为这是赛前准备，前教练称其为“另一个需要管理的应用程序”。",
                        "Luna's technique and pace are at professional trial level. She occasionally adjusts the set-piece order according to the stars; her agency calls it pre-match preparation, a former coach calls it 'one more app to manage'."),
                    L("经纪人材料 · 部分说法无法验证", "Agent material · some claims unverifiable"), playerId: "player.zodiac.luna"),
                Mail("mail.w3.uma", MailContentKind.PlayerResume, 3, L("两侧都行经纪事务所", "Either Flank Agency"), L("球员简历：乌玛·费尔南德斯", "Player résumé: Uma Fernandez"),
                    L("能踢左右翼卫，跑动和适应能力可靠。",
                        "Plays wing-back on either side; reliable stamina and adaptability."),
                    L("乌玛在四后卫和三中卫体系中都有比赛经验。她愿意踢左右两侧，唯一要求是赛前告诉她球队今天究竟打哪套阵型。",
                        "Uma has match experience in both back-four and back-three systems. She's happy on either flank; her only request is to be told before kick-off which formation the team is actually playing today."),
                    L("多家旧俱乐部推荐 · 可靠性较高", "Recommended by multiple former clubs · fairly reliable"), playerId: "player.utility.uma"),
                Mail("mail.w3.press", MailContentKind.General, 3, L("《边线周刊》编辑部", "The Touchline Weekly editorial desk"), L("传闻核对：集锦里的速度不等于九十分钟速度", "Rumour check: highlight-reel pace is not ninety-minute pace"),
                    L("本周专栏比较短视频、完整比赛和经纪人口述的差异。",
                        "This week's column compares short clips, full matches and agents' anecdotes."),
                    L("球探部门提醒，剪辑能隐藏回防、站位和比赛强度。看完十秒钟高光后，请至少再问一次：球丢掉以后这个人去了哪里？",
                        "Our scouting desk reminds readers that editing can hide tracking back, positioning and match intensity. After ten seconds of highlights, ask at least once more: where did this person go after the ball was lost?"),
                    L("独立媒体 · 方法说明", "Independent media · methodology note")),

                Mail("mail.w4.seaside", MailContentKind.ClubRequest, 4, L("海港蓝鸥 · 体育主管", "Harbour Bluegulls FC · Sporting Director"), L("短期招聘：能处理高球的门将", "Short-term opening: goalkeeper who commands high balls"),
                    L("保级球队一号门将受伤，需求仅保留两周。",
                        "A relegation battler's first-choice keeper is injured; the request stays up two weeks only."),
                    L("我们需要一名能够指挥防线、处理传中并承受密集射门的门将。主场海风很大，但请不要把所有判断失误都写进气象报告。",
                        "We need a goalkeeper who can organise the defence, deal with crosses and withstand a barrage. The sea wind at home is strong, but please don't file every misjudgement under the weather report."),
                    L("俱乐部正式招聘 · 时效较高", "Official club recruitment · time-sensitive"), demandId: "demand.week4.keeper"),
                Mail("mail.w4.gus", MailContentKind.PlayerResume, 4, L("安全手套经纪公司", "Safe Gloves Agency"), L("球员简历：格斯·贝克", "Player résumé: Gus Baker"),
                    L("高球处理稳定，训练态度可靠，点球履历有一处夸张。",
                        "Dependable on high balls, reliable trainer; one exaggeration in the penalty record."),
                    L("格斯可以立即参加试训。他确实在公开训练中扑出四粒点球；所谓第五次扑救，是第五名主罚者没有出场。",
                        "Gus is available for trial immediately. He genuinely saved four penalties in an open training session; the so-called fifth save was a fifth taker who never showed up."),
                    L("公开训练记录 · 可靠性较高", "Open training records · fairly reliable"), playerId: "player.gloves.gus"),
                Mail("mail.w4.felix", MailContentKind.PlayerResume, 4, L("职业门将协会", "Professional Goalkeepers' Association"), L("球员简历：费利克斯·文书", "Player résumé: Felix Files"),
                    L("基本功稳定、职业态度优秀，出球速度偏慢。",
                        "Sound fundamentals, excellent professionalism; distribution on the slow side."),
                    L("费利克斯重视沟通和站位，也重视每一项流程。他不会忘记训练时间，但可能要求后卫在发动反击前确认收件人。",
                        "Felix values communication and positioning — and every procedure equally. He will never forget a training time, but he may ask the defenders to confirm the addressee before launching a counter-attack."),
                    L("协会推荐 · 样本完整", "Association recommendation · complete sample"), playerId: "player.forms.felix"),
                Mail("mail.w4.dino", MailContentKind.PlayerResume, 4, L("超远界外球实验室", "The Long Throw Laboratory"), L("球员简历：迪诺·马尔凯蒂", "Player résumé: Dino Marchetti"),
                    L("边后卫，界外球距离惊人，防守纪律一般。",
                        "Full-back; astonishing throw-in distance, ordinary defensive discipline."),
                    L("迪诺把界外球当作禁区传中使用。优势是能把球送得很远；风险是有时连本队中锋也不知道球会从哪片云下面落下。",
                        "Dino uses the throw-in as a box cross. The upside: he can launch it enormous distances. The risk: sometimes even his own striker doesn't know under which cloud the ball will come down."),
                    L("专项训练报告 · 样本偏窄", "Specialist training report · narrow sample"), playerId: "player.throwin.dino"),
                Mail("mail.w4.qualifier", MailContentKind.General, 4, L("洲际赛事观察室", "Continental Competition Watch"), L("资格赛首轮结束：豪门已经开始紧张", "First qualifying round done: the giants are already nervous"),
                    L("赛季仍在季前阶段，但洲际资格赛已经制造了第一批危机会议。",
                        "The season is still in pre-season, yet continental qualifying has already produced its first crisis meetings."),
                    L("两支热门球队首回合未能获胜。电视评论员称这是战术问题，俱乐部董事会称这是体能问题，球迷认为唯一问题是夏季没有买够人。",
                        "Two favourites failed to win their first legs. Television pundits call it a tactical problem, club boards call it a fitness problem, and the fans believe the only problem is that nobody bought enough players in the summer."),
                    L("赛事新闻 · 赛季进度", "Competition news · season progress")),

                Mail("mail.w5.foundry", MailContentKind.ClubRequest, 5, L("铁炉竞技 · 主教练办公室", "Foundry Athletic · Head Coach's Office"), L("杯赛阵容补充：中后卫与前锋", "Cup squad additions: centre-back and striker"),
                    L("争夺洲际资格的球队需要两名可靠轮换，需求有效三周。",
                        "A club chasing continental qualification needs two reliable rotation players; open three weeks."),
                    L("后卫需要守纪律，前锋需要参与逼抢。我们不反对个人品牌，但摄制组、无人机和庆祝动作设计师不能一起进入训练基地。",
                        "The defender must be disciplined; the striker must join the press. We have nothing against personal brands, but camera crews, drones and celebration choreographers may not all enter the training ground together."),
                    L("俱乐部正式招聘 · 第一手信息", "Official club recruitment · first-hand information"), demandId: "demand.week5.group"),
                Mail("mail.w5.rita", MailContentKind.PlayerResume, 5, L("北方防线顾问", "Northern Defence Consultants"), L("球员简历：丽塔·哈达德", "Player résumé: Rita Haddad"),
                    L("位置感出色、处理球果断的中后卫。",
                        "A centre-back with superb positioning and decisive clearances."),
                    L("丽塔习惯先解决危险，再讨论镜头角度。她的完整比赛数据稳定，黄牌数量也低于经纪人邮件中的感叹号数量。",
                        "Rita's habit is to deal with the danger first and discuss camera angles later. Her full-match data is consistent, and her yellow-card count is lower than the exclamation-mark count in her agent's emails."),
                    L("完整比赛记录 · 可靠性高", "Full match records · highly reliable"), playerId: "player.rivet.rita"),
                Mail("mail.w5.sonny", MailContentKind.PlayerResume, 5, L("闪耀十一人娱乐", "Sparkling Eleven Entertainment"), L("球员简历：桑尼·布莱兹", "Player résumé: Sonny Blaze"),
                    L("技术动作很多，防守参与和时间观念需要核实。",
                        "Endless tricks; defensive contribution and timekeeping need verification."),
                    L("桑尼能创造普通球员想不到的处理，也会尝试教练没要求的处理。他的团队保证这次试训不会迟到，前提是开场时间适合直播。",
                        "Sonny produces solutions ordinary players can't imagine — and attempts ones his coach never requested. His team guarantees he won't be late for this trial, provided kick-off suits the livestream schedule."),
                    L("球员团队宣传 · 风险较高", "Player's team promotion · elevated risk"), playerId: "player.showboat.sonny"),
                Mail("mail.w5.nova", MailContentKind.PlayerResume, 5, L("东岸分析学院", "East Coast Analytics Institute"), L("球员简历：诺瓦·伊万诺娃", "Player résumé: Nova Ivanova"),
                    L("能在逼抢下组织进攻的数据型中场。",
                        "A data-driven midfielder who can build play under a press."),
                    L("诺瓦会把赛前分析真正带进比赛，而不是只带进会议室。她阅读压迫、寻找向前线路的能力都有完整录像支持。",
                        "Nova actually brings pre-match analysis onto the pitch rather than leaving it in the meeting room. Her ability to read pressure and find forward lanes is backed by full-match footage."),
                    L("学院与比赛数据联合报告 · 可靠性高", "Joint report from institute and match data · highly reliable"), playerId: "player.spreadsheet.nova"),
                Mail("mail.w5.camera", MailContentKind.General, 5, L("训练基地物业部", "Training Ground Facilities Department"), L("通知：球员纪录片摄制组不属于医疗设备", "Notice: player documentary crews are not medical equipment"),
                    L("本周已有三支摄制组申请进入更衣室。",
                        "Three film crews applied for dressing-room access this week alone."),
                    L("物业部再次说明：摄影机不能占用冰浴池，导演椅不能放在战术通道，“寻找真实感”也不能成为翻越围栏的理由。",
                        "Facilities would like to clarify once more: cameras may not occupy the ice bath, director's chairs may not be placed in tactical walkways, and 'searching for authenticity' is not a valid reason to climb the fence."),
                    L("基地公告 · 信息真实", "Grounds announcement · information verified")),

                Mail("mail.w6.comets", MailContentKind.ClubRequest, 6, L("彗星城 · 足球战略部", "Comet City FC · Football Strategy Department"), L("冠军阵容补强：中场与翼卫", "Champions' reinforcement: midfielder and wing-back"),
                    L("卫冕冠军为双线赛程寻找轮换球员，需求有效四周。",
                        "The reigning champions seek rotation players for a two-front schedule; open four weeks."),
                    L("我们需要一名能在高压下组织进攻的中场，以及一名覆盖整条边路的翼卫。数据部门会提供模型，但最终仍由教练看球。",
                        "We need a midfielder who can build attacks under a high press and a wing-back who covers the whole flank. The data department will supply the models, but in the end the coach still watches the football."),
                    L("俱乐部正式招聘 · 第一手信息", "Official club recruitment · first-hand information"), demandId: "demand.week6.future"),
                Mail("mail.w6.echo", MailContentKind.PlayerResume, 6, L("双足体育", "Two Feet Sports"), L("球员简历：艾可·摩根", "Player résumé: Echo Morgan"),
                    L("左右脚均衡、能够胜任两侧的翼卫。",
                        "A genuinely two-footed wing-back at home on either flank."),
                    L("艾可在两侧都有完整比赛样本，回追和套边能力稳定。经纪人唯一没有回答的问题，是她更愿意坐球队大巴左边还是右边。",
                        "Echo has full-match samples on both flanks, with consistent recovery runs and overlaps. The one question her agent never answered: whether she prefers the left or right side of the team bus."),
                    L("多场比赛记录 · 可靠性高", "Multiple match records · highly reliable"), playerId: "player.bothfeet.echo"),
                Mail("mail.w6.scout", MailContentKind.General, 6, L("冠军联赛球探圆桌", "Champions League Scout Roundtable"), L("观察笔记：高位防线最怕的不是慢，是判断慢", "Scout notes: the high line's worst enemy isn't slow legs, it's slow reading"),
                    L("洲际赛事对空间处理和决策速度要求更高。",
                        "Continental competition demands more of spatial awareness and decision speed."),
                    L("评价后卫时，不要只看百米速度。提前移动、保护身后和与门将沟通，往往比一次漂亮的回追更能说明问题。",
                        "When judging a defender, don't stop at the hundred-metre time. Moving early, protecting the space behind and talking to the keeper often say more than one spectacular recovery run."),
                    L("专业讨论 · 可作为判断依据", "Expert discussion · usable as a basis for judgement")),
                Mail("mail.w6.finance", MailContentKind.General, 6, L("事务所财务", "Agency Accounts"), L("应收款提醒：已成交不等于已到账", "Receivables reminder: closed is not the same as paid"),
                    L("结果与付款可能跨周到达，请分别查看现金和应收。",
                        "Results and payments may arrive weeks apart; check cash and receivables separately."),
                    L("俱乐部确认试训后，顾问费会进入应收款；预计到账周到来后才计入现金。请不要拿尚未到账的钱预订赛季末庆功宴。",
                        "Once a club confirms a trial, the consultancy fee enters receivables; it only counts as cash when the expected payment week arrives. Please do not book the end-of-season banquet with money that hasn't landed."),
                    L("系统规则 · 可直接信赖", "System rules · fully reliable")),
                Mail("mail.w6.calendar", MailContentKind.General, 6, L("联盟赛程中心", "League Fixture Centre"), L("季前阶段即将结束：联赛开幕倒计时", "Pre-season nearly over: countdown to opening day"),
                    L("下周开始进入夏季窗口与联赛准备的密集阶段。",
                        "Next week begins the congested stretch of summer window and league preparation."),
                    L("俱乐部将陆续公布号码、注册名单和最后热身赛。赛程中心提醒各队：把友谊赛输球称为“负荷管理”不会改变比分。",
                        "Clubs will announce squad numbers, registration lists and final friendlies in turn. The fixture centre reminds everyone: calling a friendly defeat 'load management' does not change the scoreline."),
                    L("联盟公告 · 赛季进度", "League announcement · season progress"))
            };

            AddSeasonProgressMails(mails);
            AddExpiryMails(mails, players, demands);
            return mails;
        }

        public static List<MagazineIssueContent> BuildMagazineIssues()
        {
            return new List<MagazineIssueContent>
            {
                Issue("mag.touchline.01", 0, 1, L("《边线周刊》", "The Touchline Weekly"), L("资格赛前的前锋市场", "The striker market before the qualifiers"), "01",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("四十一球到底在哪儿？", "Where Exactly Are the Forty-One Goals?"), L("从经纪人数字回到完整比赛。", "From agent arithmetic back to full matches."),
                        L("一名前锋的宣传材料写着四十一球，但没有联赛名称、出场数和比赛级别。数字越整齐，越应该先问统计口径。",
                            "A striker's promo material says forty-one goals, but gives no league name, appearance count or level of competition. The rounder the number, the sooner you should ask about the methodology."),
                        L("雨城竞技需要的是能立刻适应资格赛强度的前锋。跑位、逼抢和身体状态，比一张孤立的射手榜截图更重要。",
                            "Rainy City Athletic need a striker who can handle qualifying intensity from day one. Movement, pressing and physical condition matter more than a lone screenshot of a scoring chart."),
                        L("“球探不是来证明邮件正确，而是来判断哪里可能不正确。”", "'A scout's job is not to prove the email right, but to judge where it might be wrong.'"), L("核对清单", "Checklist"), L("赛事级别、出场分钟、点球占比、完整录像。", "Competition level, minutes played, penalty share, full-match footage."), "player.rocket.rory"),
                    Page(MagazinePageLayout.Feature, L("战术室", "Tactics Room"), L("资格赛为什么比热身赛快半拍", "Why Qualifiers Run Half a Beat Faster Than Friendlies"), L("高压比赛首先考验决策。", "High-pressure matches test decisions first."),
                        L("洲际资格赛的空间更小，转换更快。前锋如果只等待最后一脚，球队很容易在第一道逼抢就少一人。",
                            "Continental qualifiers offer smaller spaces and faster transitions. A striker who only waits for the final touch leaves his team a man down against the first line of the press."),
                        L("观察候选人时，应记录他丢球后的五秒、无球跑动和与中场的距离，而不只是射门。",
                            "When watching candidates, log the five seconds after they lose the ball, their off-ball runs and their distance from midfield — not just the shooting."),
                        L("“速度是到达空间，判断是提前知道空间会出现。”", "'Pace is arriving in space; judgement is knowing the space will appear.'"), L("雨城竞技", "Rainy City Athletic"), L("上季第四，目标进入洲际冠军联赛正赛。", "Fourth last season; aiming for the Continental Champions League proper."), "player.rocket.rory", 3, 4),
                    Page(MagazinePageLayout.ScoutReport, L("球探报告", "Scout Report"), L("罗里·奎克：跑位可信，数字待查", "Rory Quick: Movement Checks Out, Numbers Pending"), L("公开信息的可信部分与空白部分。", "The credible parts of the public record — and the blank parts."),
                        L("两场完整录像证明他的反越位和启动具备职业水准。",
                            "Two full recordings prove his beating of the offside trap and his acceleration are professional standard."),
                        L("没有证据支持四十一球，也没有证据说明比赛强度足以对应顶级联赛。",
                            "No evidence supports the forty-one goals, nor that the competition's intensity maps to a top league."),
                        L("“可以推荐试训，但不能把宣传数字当结论。”", "'Worth recommending for a trial — but a promotional number is not a conclusion.'"), L("风险", "Risks"), L("样本量小；经纪人叙述明显偏向球员。", "Small sample; agent's account clearly favours the player."), "player.rocket.rory", 7),
                    Page(MagazinePageLayout.Feature, L("文化页", "Culture Page"), L("当每支球队都说自己在重建", "When Every Club Says It's Rebuilding"), L("季前发布会常用词观察。", "A field guide to pre-season press-conference vocabulary."),
                        L("长期计划、年轻化和回归传统是最常见的三句话。",
                            "'Long-term plan', 'youth movement' and 'back to our traditions' are the three most common sentences."),
                        L("如果同一周出现第四位“最后一块拼图”，请检查俱乐部是否还保留前三块的收据。",
                            "If a fourth 'final piece of the puzzle' appears in the same week, check whether the club kept the receipts for the first three."),
                        L("“足球没有最终版文件，只有下一次修改。”", "'Football has no final-version document, only the next revision.'"), L("本周术语", "Term of the Week"), L("负荷管理：热身赛输球后的常用解释。", "Load management: the standard explanation after losing a friendly."), "", 8, 19)),
                Issue("mag.touchline.02", 1, 2, L("《边线周刊》", "The Touchline Weekly"), L("中场价值与看不见的工作", "Midfield Value and the Invisible Work"), "02",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("为什么最重要的传球常常进不了集锦", "Why the Most Important Pass Rarely Makes the Highlight Reel"), L("米洛式中场的观看方法。", "How to watch a Milo-type midfielder."),
                        L("安全接应、调整站位和吸引逼抢很少成为短视频标题。",
                            "Safe outlets, positional adjustments and drawing the press rarely become short-video titles."),
                        L("但这些动作决定球队能否把一次控球变成稳定推进。",
                            "Yet these actions decide whether a team turns one possession into steady progress."),
                        L("“好的中场让队友看起来都早到了一秒。”", "'A good midfielder makes every teammate look a second early.'"), L("观察重点", "Watch For"), L("接球前扫描、身体朝向、丢球后的回位。", "Scanning before receiving, body shape, recovery after losing the ball."), "player.metronome.milo"),
                    Page(MagazinePageLayout.Feature, L("比赛分析", "Match Analysis"), L("船坞联需要的是连接，不是第二个前锋", "Dockyard United Need Connection, Not a Second Striker"), L("双人招聘的结构逻辑。", "The structural logic of a two-man recruitment."),
                        L("前锋负责威胁纵深，中场负责让威胁持续存在。",
                            "The striker threatens the depth; the midfielder makes the threat sustainable."),
                        L("如果两人都只追求最后一脚，球队会像散开的集装箱一样失去联系。",
                            "If both only chase the final touch, the team loses contact like shipping containers scattered off the manifest."),
                        L("“组合价值不等于两份个人集锦相加。”", "'A partnership's value is not two highlight reels added together.'"), L("俱乐部档案", "Club Profile"), L("上季第十一，定位球强，运动战组织不足。", "Eleventh last season; strong on set pieces, short of open-play structure."), "player.metronome.milo", 3, 5),
                    Page(MagazinePageLayout.ScoutReport, L("老将观察", "Veteran Watch"), L("维克：速度下降之后还剩什么", "Vic: What's Left After the Pace Goes"), L("六码区经验是否仍有市场。", "Is six-yard-box experience still on the market?"),
                        L("维克的冲刺频率明显下降，但对二点球和解围落点的判断仍然可靠。",
                            "Vic's sprint frequency has dropped markedly, but his reading of second balls and where clearances drop remains reliable."),
                        L("需要持续高位压迫的球队应谨慎；需要短时间禁区效率的球队可以试训。",
                            "Teams needing a constant high press should be cautious; teams needing short bursts of box efficiency should trial him."),
                        L("“老将的价值不是跑得和年轻人一样快。”", "'A veteran's value is not running as fast as the kids.'"), L("适配条件", "Fit Conditions"), L("有限出场时间、明确禁区职责、合理轮换。", "Limited minutes, a clear box role, sensible rotation."), "player.thermos.vic", 16),
                    Page(MagazinePageLayout.Feature, L("数据页", "Data Page"), L("完整比赛比热区更会说话", "A Full Match Talks Better Than a Heat Map"), L("别让一张图替你看完九十分钟。", "Don't let one image watch ninety minutes for you."),
                        L("热区能说明球员在哪里触球，却不一定说明他为什么在那里。",
                            "A heat map shows where a player touches the ball; it doesn't necessarily show why he was there."),
                        L("把数据与比赛阶段、比分和对手强度放在一起，结论才有意义。",
                            "Only alongside match phase, scoreline and opponent strength does data support a conclusion."),
                        L("“没有上下文的数据，只是穿西装的传闻。”", "'Data without context is just gossip in a suit.'"), L("本周提醒", "Reminder of the Week"), L("先问样本，再问结论。", "Ask about the sample before the conclusion."), "", 23, 7)),
                Issue("mag.touchline.03", 2, 3, L("《欧陆足球观察》", "The Continental Football Observer"), L("豪门补强与高位防线", "Reinforcement at the Giants and the High Line"), "03",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("传统豪门需要怎样的中后卫", "What Kind of Centre-Back Does a Traditional Giant Need"), L("高位防线把判断放大。", "A high line magnifies judgement."),
                        L("争冠球队的中后卫常在更大空间里防守。",
                            "A title contender's centre-back often defends in much larger spaces."),
                        L("正面对抗强不等于适合所有体系，提前移动和转身同样重要。",
                            "Dominance in head-on duels doesn't fit every system; moving early and turning matter just as much."),
                        L("“高位防线不会隐藏短板，只会给短板更大的草地。”", "'A high line doesn't hide your weaknesses; it gives them a bigger meadow.'"), L("旧堡王冠", "Oldcastle Crown FC"), L("上季第二，连续六年参加洲际冠军联赛。", "Second last season; six straight years in the Continental Champions League."), "player.wall.walter"),
                    Page(MagazinePageLayout.Feature, L("战术室", "Tactics Room"), L("边锋的一对一不是个人表演", "A Winger's One-on-One Is Not a Solo Act"), L("突破必须连接后续进攻。", "A dribble must connect to what comes next."),
                        L("真正有效的一对一会迫使防线移动，为队友创造射门或传中空间。",
                            "A truly effective one-on-one forces the defence to shift, creating shooting or crossing space for teammates."),
                        L("只有动作没有后续选择，往往只是把丢球地点向前移动十米。",
                            "Tricks without a follow-up option usually just move the turnover location ten metres upfield."),
                        L("“过掉第一个人以后，比赛才刚开始。”", "'After you beat the first man, the match has only just begun.'"), L("观察重点", "Watch For"), L("抬头频率、弱侧队友、丢球反应。", "How often he lifts his head, weak-side teammates, reaction to losing the ball."), "player.zodiac.luna", 3, 10),
                    Page(MagazinePageLayout.ScoutReport, L("球探报告", "Scout Report"), L("沃尔特：禁区可靠，高位有问号", "Walter: Reliable in the Box, Question Marks Higher Up"), L("强项明确，体系适配需要试训。", "Clear strengths; system fit requires a trial."),
                        L("沃尔特在禁区附近的对抗和解围值得信任。",
                            "Walter's duels and clearances around the box can be trusted."),
                        L("当防线压到中线，他的转身和追踪线路可能成为风险。",
                            "When the line pushes up to halfway, his turning and tracking runs become a risk."),
                        L("“不是能力不足，而是问题必须问对。”", "'Not a lack of ability — the questions must be asked correctly.'"), L("建议", "Recommendation"), L("安排高位防线专项试训，不以亲属评价作结论。", "Arrange a high-line-specific trial; do not conclude from relatives' reviews."), "player.wall.walter", 7),
                    Page(MagazinePageLayout.Feature, L("看台文化", "Terrace Culture"), L("每份五年计划为什么只活到星期五", "Why Every Five-Year Plan Only Lives Until Friday"), L("豪门董事会语言学。", "The linguistics of a big club's boardroom."),
                        L("成绩好时叫延续，成绩差时叫重建。",
                            "When results are good it's 'continuity'; when they're bad it's 'rebuilding'."),
                        L("计划本身通常没有问题，问题是文件名里的“最终版”已经出现八次。",
                            "The plans themselves are usually fine; the problem is the filename has contained 'FINAL' eight times."),
                        L("“长期主义的最短单位，是下一场比赛。”", "'The shortest unit of long-termism is the next match.'"), L("词汇表", "Glossary"), L("全面支持：通常持续到下一次主场嘘声。", "Full backing: typically lasts until the next round of home booing."), "", 19, 4)),
                Issue("mag.touchline.04", 3, 4, L("《门线月报》", "The Goal Line Monthly"), L("门将、传中与第五粒点球", "Goalkeepers, Crosses and the Fifth Penalty"), "04",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("五连扑传说的第五个人去哪了", "Five Saves in a Row: Where Did the Fifth Man Go"), L("漂亮数字也要核对出场名单。", "Even pretty numbers must be checked against the teamsheet."),
                        L("格斯确实完成四次扑救，这是很强的表现。",
                            "Gus really did make four saves — a genuinely strong showing."),
                        L("第五名主罚者没有出场，因此不能把缺席统计成一次扑救。",
                            "The fifth taker never appeared, and an absence cannot be recorded as a save."),
                        L("“好球探不会因为笑话有趣就停止核实。”", "'A good scout doesn't stop verifying just because the joke is funny.'"), L("门将指标", "Goalkeeper Metrics"), L("站位、二次反应、高球判断、出球选择。", "Positioning, second reactions, high-ball judgement, distribution choices."), "player.gloves.gus"),
                    Page(MagazinePageLayout.Feature, L("门将课堂", "Goalkeeper Classroom"), L("海风不是技术指标", "Sea Wind Is Not a Technical Metric"), L("处理传中需要可重复的判断。", "Dealing with crosses needs repeatable judgement."),
                        L("风会影响球路，但门将仍需通过站位、启动和沟通降低不确定性。",
                            "Wind bends the ball, but a keeper still reduces uncertainty through positioning, timing and communication."),
                        L("把每次失误归因于天气，只会让下一次失误更准时地到来。",
                            "Blaming every error on the weather only makes the next error arrive more punctually."),
                        L("“环境能解释难度，不能替代责任。”", "'Conditions explain difficulty; they don't replace responsibility.'"), L("海港蓝鸥", "Harbour Bluegulls FC"), L("上季附加赛保级，禁区防守压力大。", "Survived via the play-offs last season; heavy pressure on their box."), "player.gloves.gus", 17, 13),
                    Page(MagazinePageLayout.ScoutReport, L("球探报告", "Scout Report"), L("费利克斯：可靠，但反击需要少一张表", "Felix: Reliable, but Counters Need One Form Fewer"), L("职业性很高，节奏偏慢。", "Highly professional; tempo on the slow side."),
                        L("费利克斯的站位和基础扑救稳定，训练记录也很完整。",
                            "Felix's positioning and basic shot-stopping are steady, and his training records are immaculate."),
                        L("快速出球时存在犹豫，适合强调控制而非持续转换的球队。",
                            "There is hesitation in quick distribution; he suits control-first teams over constant transition."),
                        L("“手续齐全不会丢球，但也不会自动制造反击。”", "'Complete paperwork never loses the ball — but it doesn't launch a counter-attack either.'"), L("建议", "Recommendation"), L("试训加入快速手抛球和长传决策。", "Include quick throws and long-pass decisions in the trial."), "player.forms.felix", 17),
                    Page(MagazinePageLayout.Feature, L("规则角", "Rules Corner"), L("界外球可以很远，不能离开球场", "A Throw-In Can Be Long, but It Must Stay in the Stadium"), L("迪诺专项观察。", "A specialist note on Dino."),
                        L("超远界外球能创造禁区压力，但落点必须可预测。",
                            "An enormous throw can pile pressure on the box, but the landing spot must be predictable."),
                        L("如果队友也在寻找皮球，战术突然性就已经用过头了。",
                            "If his teammates are also searching for the ball, the element of surprise has been overdrawn."),
                        L("“距离是武器，控制才是瞄准器。”", "'Distance is the weapon; control is the sight.'"), L("样本风险", "Sample Risk"), L("专项集锦无法替代防守录像。", "A specialist reel can't replace defensive footage."), "player.throwin.dino", 11, 3)),
                Issue("mag.touchline.05", 4, 5, L("《九十分钟》", "Ninety Minutes"), L("纪律、压迫与摄制组", "Discipline, Pressing and Camera Crews"), "05",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("没有镜头时还愿不愿意回防", "Will He Track Back When the Cameras Are Off"), L("铁炉竞技的招聘标准。", "Foundry Athletic's recruitment standard."),
                        L("杯赛球队需要能执行重复任务的球员。",
                            "A cup team needs players who will execute repetitive tasks."),
                        L("压迫、补位和保护二点球不漂亮，却决定淘汰赛能走多远。",
                            "Pressing, covering and winning second balls aren't pretty, but they decide how far a knockout run goes."),
                        L("“职业性，是镜头转开以后仍然做正确的事。”", "'Professionalism is doing the right thing after the camera pans away.'"), L("铁炉竞技", "Foundry Athletic"), L("上季第七，两次国内杯冠军。", "Seventh last season; two domestic cup titles."), "player.rivet.rita"),
                    Page(MagazinePageLayout.Feature, L("防守课", "Defending Lesson"), L("丽塔为什么很少出现在失误集锦里", "Why Rita Rarely Appears in Error Compilations"), L("位置感的价值是让危险不发生。", "The value of positioning is that the danger never happens."),
                        L("她不会为了抢镜离开防区，处理危险球也很直接。",
                            "She won't vacate her zone for the cameras, and she deals with danger directly."),
                        L("这类后卫的优秀表现通常是一场比赛没有发生值得剪辑的事故。",
                            "A great game from this kind of defender usually means nothing clip-worthy happened at all."),
                        L("“最好的解围，有时是提前两步让传球根本进不来。”", "'The best clearance is sometimes stepping up two paces so the pass never arrives.'"), L("可靠性", "Reliability"), L("多场完整录像与不同来源评价一致。", "Multiple full recordings and independent sources agree."), "player.rivet.rita", 3, 6),
                    Page(MagazinePageLayout.ScoutReport, L("风险报告", "Risk Report"), L("桑尼：灵感很贵，纪律也有价格", "Sonny: Inspiration Is Expensive, and Discipline Has a Price Too"), L("能力与可用性必须一起评估。", "Ability and availability must be assessed together."),
                        L("桑尼能完成高难度动作，也会忽略简单的跑位要求。",
                            "Sonny can pull off the hardest moves, and ignore the simplest run."),
                        L("如果球队没有管理空间，他的个人亮点可能抵不过无球阶段的损失。",
                            "Without room to manage him, his personal highlights may not cover what he costs off the ball."),
                        L("“不是所有穿裆都能进入积分榜。”", "'Not every nutmeg makes it into the league table.'"), L("试训建议", "Trial Advice"), L("记录准时性、无球跑动和丢球后的反应。", "Log punctuality, off-ball running and reactions after losing possession."), "player.showboat.sonny", 11),
                    Page(MagazinePageLayout.Feature, L("媒体页", "Media Page"), L("纪录片不是球探报告", "A Documentary Is Not a Scout Report"), L("摄像机改变人们展示自己的方式。", "A camera changes how people present themselves."),
                        L("球员知道镜头存在时，会更愿意尝试可传播的动作。",
                            "Knowing the lens is there, players reach for the shareable move."),
                        L("因此需要无剪辑训练、完整比赛和不同来源的观察。",
                            "Hence the need for uncut training sessions, full matches and independent observers."),
                        L("“真实感不能由导演喊开始。”", "'Authenticity doesn't start when the director calls action.'"), L("基地规定", "Ground Rules"), L("无人机不得进入定位球训练。", "Drones are barred from set-piece training."), "", 8, 7)),
                Issue("mag.touchline.06", 5, 6, L("《冠军之路》", "The Road to Glory"), L("双线赛程的轮换答案", "Rotation Answers for a Two-Front Season"), "06",
                    Page(MagazinePageLayout.Cover, L("封面故事", "Cover Story"), L("冠军球队为何仍然需要补强", "Why Champions Still Need Reinforcements"), L("联赛与洲际赛事需要不同的体能账本。", "League and continental fixtures require different fitness ledgers."),
                        L("卫冕冠军面对更多高强度比赛，轮换不是替补席人数问题。",
                            "Reigning champions face more high-intensity matches; rotation is not a matter of bench headcount."),
                        L("球员必须能在不同对手和不同比赛状态下完成明确职责。",
                            "Players must deliver defined roles against different opponents and in different match states."),
                        L("“冠军阵容不是一张合影，而是一整季都能用的工具箱。”", "'A title squad is not a group photo; it's a toolbox that works all season.'"), L("彗星城", "Comet City FC"), L("卫冕冠军，洲际冠军联赛夺冠热门。", "Reigning champions; favourites for the Continental Champions League."), "player.bothfeet.echo"),
                    Page(MagazinePageLayout.Feature, L("战术室", "Tactics Room"), L("翼卫为什么像两份工作", "Why Wing-Back Is Two Jobs"), L("一条边路的攻防都写在职位说明里。", "Both ends of a flank are written into the job description."),
                        L("翼卫需要提供宽度、回追、协防和反击出口。",
                            "A wing-back must supply width, recovery runs, cover defence and a counter-attacking outlet."),
                        L("能踢两侧的球员会提高阵容弹性，但必须确认左右脚能力不是宣传用语。",
                            "A player who can play both flanks adds squad flexibility — but first confirm the two-footedness isn't a marketing phrase."),
                        L("“覆盖全场不等于无目的地跑遍全场。”", "'Covering the whole pitch is not the same as running all over it without purpose.'"), L("观察重点", "Watch For"), L("回追路线、弱侧站位、连续冲刺恢复。", "Recovery lines, weak-side positioning, repeat-sprint recovery."), "player.bothfeet.echo", 3, 6),
                    Page(MagazinePageLayout.ScoutReport, L("球探报告", "Scout Report"), L("诺瓦：数据不是她唯一的语言", "Nova: Data Isn't Her Only Language"), L("高压下处理球的样本可靠。", "A reliable sample of playing under pressure."),
                        L("诺瓦能在逼抢到来前调整身体朝向，并主动寻找向前线路。",
                            "Nova adjusts her body shape before the press arrives and actively seeks forward lanes."),
                        L("她的数据习惯是额外工具，而不是掩盖比赛能力的包装。",
                            "Her data habits are an extra tool, not packaging that hides the football."),
                        L("“真正的数据型球员，首先仍然是球员。”", "'A true data-driven player is a player first.'"), L("适配", "Best Fit"), L("适合需要控制节奏和压迫下出球的球队。", "Suits teams that need tempo control and playing out under pressure."), "player.spreadsheet.nova", 23),
                    Page(MagazinePageLayout.Feature, L("赛程页", "Fixture Page"), L("从季前训练走向五十二周", "From Pre-Season to Week Fifty-Two"), L("一年不会只发生在转会窗口。", "A year doesn't happen only in transfer windows."),
                        L("联赛开幕、洲际小组赛、冬季窗口、淘汰赛和争冠保级会依次到来。",
                            "Opening day, continental group games, the winter window, knockout rounds and the title-and-relegation run-in will arrive in turn."),
                        L("关注顶部日期和赛事邮件，不需要自己换算第几周。",
                            "Watch the date at the top and the competition mails — no need to convert week numbers yourself."),
                        L("“赛季很长，但每个截止日都来得比体育主管想象中快。”", "'The season is long, but every deadline arrives faster than the sporting director imagines.'"), L("下一阶段", "Next Phase"), L("夏季窗口与联赛开幕。", "The summer window and opening day."), "", 4, 12))
            };
        }

        private static void AddSeasonProgressMails(List<MailContentEntry> mails)
        {
            mails.AddRange(new[]
            {
                SeasonMail("mail.season.w7", 7, L("联盟赛程中心", "League Fixture Centre"), L("联赛开幕月：新赛季正式进入比赛节奏", "Opening month: the new season finds its rhythm"),
                    L("热身赛结束，联赛注册名单陆续公布。接下来几周，球队会在补强冲动和财务现实之间反复横跳。",
                        "Friendlies are over and league registration lists are being published. Over the next few weeks, clubs will bounce repeatedly between the urge to strengthen and financial reality.")),
                SeasonMail("mail.season.w10", 10, L("转会窗口办公室", "Transfer Window Office"), L("夏季窗口关闭：传真机再次幸存", "Summer window closed: the fax machine survives again"),
                    L("注册通道已经关闭。最后一分钟提交的文件中，有两份缺签名、一份咖啡渍，以及一张明显属于餐厅的菜单。",
                        "The registration channel is closed. Among the last-minute submissions: two missing signatures, one coffee stain, and a menu that clearly belongs to a restaurant.")),
                SeasonMail("mail.season.w14", 14, L("洲际赛事组委会", "Continental Competition Organising Committee"), L("冠军联赛阶段开打：周中夜赛开始", "Champions League stage begins: midweek nights are here"),
                    L("联赛之外的洲际赛程正式开始。阵容深度、旅行恢复和客场抗压将逐渐影响招聘口径。",
                        "The continental calendar alongside the league has officially begun. Squad depth, travel recovery and away resilience will gradually reshape recruitment briefs.")),
                SeasonMail("mail.season.w18", 18, L("足球新闻台", "Football News Channel"), L("秋季密集赛程：伤病名单开始比首发名单长", "Autumn congestion: the injury list starts outgrowing the teamsheet"),
                    L("连续一周双赛让各队重新理解“轮换”的意义。部分体育主管已经开始给冬季目标发并不隐秘的问候。",
                        "Back-to-back two-match weeks have clubs rediscovering what 'rotation' means. Some sporting directors are already sending not-especially-secret greetings to winter targets.")),
                SeasonMail("mail.season.w22", 22, L("洲际赛事组委会", "Continental Competition Organising Committee"), L("小组阶段收官：有人晋级，有人开始解释", "Group stage finale: some advance, some start explaining"),
                    L("晋级球队讨论淘汰赛签位，出局球队讨论赛制、草皮、天气和统计口径。没有人讨论夏天那份过度自信的演示文档。",
                        "The qualifiers discuss knockout draws; the eliminated discuss the format, the pitch, the weather and statistical methodology. Nobody discusses the summer's overconfident slide deck.")),
                SeasonMail("mail.season.w26", 26, L("联盟竞赛部", "League Competitions Department"), L("节日赛程：四天一场，睡眠属于技术统计", "Festive schedule: a match every four days, sleep becomes a statistic"),
                    L("密集联赛进入最困难阶段。球队需要控制伤病和体能，而不是把所有疲劳都解释成球员缺乏求胜欲。",
                        "The congested league stretch enters its hardest phase. Teams need to manage injuries and energy, not explain away all fatigue as a lack of desire.")),
                SeasonMail("mail.season.w29", 29, L("冬季注册窗口", "Winter Registration Window"), L("冬季窗口开启：补洞、豪赌与租借", "Winter window opens: patching, gambling and loans"),
                    L("俱乐部可以再次注册新球员。谨慎的球队修补阵容，焦虑的球队修改整个计划，富有的球队两件事一起做。",
                        "Clubs may register new players again. The careful patch the squad, the anxious rewrite the whole plan, and the wealthy do both at once.")),
                SeasonMail("mail.season.w32", 32, L("冬季注册窗口", "Winter Registration Window"), L("冬季窗口关闭：所有人都说完成了主要目标", "Winter window closed: everyone says they hit their main targets"),
                    L("窗口已经关闭。没有买到人的球队称赞现有阵容，买了很多人的球队强调市场机会不可错过。",
                        "The window is closed. Clubs that bought nobody praise their existing squad; clubs that bought plenty stress that market opportunities must not be missed.")),
                SeasonMail("mail.season.w36", 36, L("洲际赛事组委会", "Continental Competition Organising Committee"), L("淘汰赛阶段：一个失误可以写进整年纪录片", "Knockout stage: one mistake can fill a whole year's documentary"),
                    L("两回合淘汰赛开始。客场应对、领先后的控制和落后时的决策，会比普通联赛更放大球员特点。",
                        "Two-legged knockout ties begin. Handling away legs, controlling a lead and deciding while behind will magnify a player's traits far more than an ordinary league match.")),
                SeasonMail("mail.season.w40", 40, L("联盟数据中心", "League Data Centre"), L("联赛进入冲刺：积分榜开始拒绝礼貌", "Run-in begins: the table stops being polite"),
                    L("争冠、欧战资格和保级区逐渐成形。每支球队都说只关注下一场，但所有办公室都开着积分计算表。",
                        "The title race, the European places and the relegation zone are taking shape. Every club says it's only focused on the next match; every office has a points spreadsheet open.")),
                SeasonMail("mail.season.w44", 44, L("杯赛委员会", "Cup Committee"), L("杯赛半决赛周：替补席深度接受检查", "Cup semi-final week: bench depth under inspection"),
                    L("淘汰赛没有平均值。一次定位球、一次扑救或一次错误换人，都可能决定整季叙事。",
                        "Knockout football has no averages. One set piece, one save or one wrong substitution can decide the entire season's narrative.")),
                SeasonMail("mail.season.w48", 48, L("足球新闻台", "Football News Channel"), L("冠军联赛决赛月与国内联赛最后冲刺", "Champions League final month and the domestic run-in"),
                    L("赛季最重要的比赛集中到来。争冠球队谈冷静，保级球队谈奇迹，中游球队开始发布下赛季球衣。",
                        "The season's biggest matches arrive all at once. Title contenders talk about calm, relegation candidates talk about miracles, and mid-table clubs start launching next season's kit.")),
                SeasonMail("mail.season.w52", 52, L("联盟主席办公室", "League President's Office"), L("赛季结束：年度结算将在本周完成", "Season over: annual settlement concludes this week"),
                    L("最后一轮已经结束。请处理本周事务，随后事务所会结算现金、应收、声望和全年安排记录。",
                        "The final round has been played. Please handle this week's business; the agency will then settle cash, receivables, reputation and the year's placement records."))
            });
        }

        private static void AddExpiryMails(
            List<MailContentEntry> mails,
            IReadOnlyList<PlayerContentEntry> players,
            IReadOnlyList<DemandContentEntry> demands)
        {
            foreach (var player in players)
            {
                mails.Add(new MailContentEntry
                {
                    id = "mail.expiry." + player.id,
                    kind = MailContentKind.General,
                    publishedWeek = player.LastAvailableWeek + 1,
                    sender = L("球员动态中心", "Player Updates Desk"),
                    subject = player.expiryMailSubject,
                    preview = L("该球员已经离开可安排名单。", "This player has left the availability list."),
                    body = player.expiryMailBody,
                    sourceNote = L("状态变更 · 球员不再可安排", "Status change · player no longer available for placement"),
                    expiredPlayerId = player.id
                });
            }

            foreach (var demand in demands)
            {
                mails.Add(new MailContentEntry
                {
                    id = "mail.expiry." + demand.id,
                    kind = MailContentKind.General,
                    publishedWeek = demand.DeadlineWeek + 1,
                    sender = demand.clubDisplayName,
                    subject = demand.expiryMailSubject,
                    preview = L("该招聘需求已经过期并从工作台移除。", "This recruitment request has expired and been removed from the workbench."),
                    body = demand.expiryMailBody,
                    sourceNote = L("俱乐部通知 · 招聘需求已关闭", "Club notice · recruitment request closed"),
                    expiredDemandId = demand.id
                });
            }
        }

        private static PlayerContentEntry Player(
            string id, int portraitIndex, int availableFromWeek, int availabilityWeeks,
            LocalizedText name, PlayerPosition position, int ability, int fitness, int professionalism,
            int salaryMinWeekly, int salaryMaxWeekly, LocalizedText careerHistory,
            LocalizedText biography, LocalizedText claim, LocalizedText evidence, EvidenceReliability reliability,
            LocalizedText expirySubject, LocalizedText expiryBody)
        {
            return new PlayerContentEntry
            {
                id = id,
                portraitIndex = portraitIndex,
                availableFromWeek = availableFromWeek,
                availabilityWeeks = availabilityWeeks,
                displayName = name,
                biography = biography,
                publicPosition = position,
                hiddenAbility = ability,
                hiddenFitness = fitness,
                hiddenProfessionalism = professionalism,
                salaryMinWeekly = salaryMinWeekly,
                salaryMaxWeekly = salaryMaxWeekly,
                careerHistory = careerHistory,
                publicClaim = claim,
                publicEvidence = evidence,
                evidenceReliability = reliability,
                expiryMailSubject = expirySubject,
                expiryMailBody = expiryBody
            };
        }

        private static DemandContentEntry Demand(
            string id, string clubId, LocalizedText clubName, LocalizedText standing, LocalizedText bestAchievement,
            LocalizedText clubProfile, LocalizedText title, LocalizedText description, int openedWeek, int activeWeeks,
            int reward, LocalizedText paymentTerms, LocalizedText expirySubject, LocalizedText expiryBody,
            params DemandSlotContentEntry[] slots)
        {
            return new DemandContentEntry
            {
                id = id,
                clubId = clubId,
                clubDisplayName = clubName,
                clubStanding = standing,
                clubBestAchievement = bestAchievement,
                clubProfile = clubProfile,
                title = title,
                description = description,
                openedWeek = openedWeek,
                activeWeeks = activeWeeks,
                baseReward = reward,
                paymentTerms = paymentTerms,
                expiryMailSubject = expirySubject,
                expiryMailBody = expiryBody,
                slots = new List<DemandSlotContentEntry>(slots)
            };
        }

        private static DemandSlotContentEntry Slot(
            string id, PlayerPosition position, int ability, int fitness, int professionalism)
        {
            return new DemandSlotContentEntry
            {
                id = id,
                requiredPosition = position,
                minimumAbility = ability,
                preferredFitness = fitness,
                preferredProfessionalism = professionalism,
                isRequired = true
            };
        }

        private static MailContentEntry Mail(
            string id, MailContentKind kind, int week, LocalizedText sender, LocalizedText subject,
            LocalizedText preview, LocalizedText body, LocalizedText source,
            string playerId = "", string demandId = "", int offer = 0,
            LocalizedText offerTerms = null, string requiredClubId = "", LocalizedText targetClub = null,
            LocalizedText risk = null)
        {
            return new MailContentEntry
            {
                id = id,
                kind = kind,
                publishedWeek = week,
                sender = sender,
                subject = subject,
                preview = preview,
                body = body,
                sourceNote = source,
                relatedPlayerId = playerId,
                relatedDemandId = demandId,
                privateOfferAmount = offer,
                privateOfferTerms = offerTerms ?? L(null, null),
                privateRequiredClubId = requiredClubId,
                privateTargetClubRequirement = targetClub ?? L(null, null),
                privateRiskNote = risk ?? L(null, null)
            };
        }

        private static MailContentEntry SeasonMail(
            string id, int week, LocalizedText sender, LocalizedText subject, LocalizedText body)
        {
            return Mail(id, MailContentKind.General, week, sender, subject,
                body, body, L("赛事与赛季进度通知", "Competition and season progress notice"));
        }

        private static MagazineIssueContent Issue(
            string id, int coverIndex, int week, LocalizedText publication, LocalizedText title,
            string issueNumber, params MagazinePageContent[] pages)
        {
            return new MagazineIssueContent
            {
                id = id,
                coverIndex = coverIndex,
                publishedWeek = week,
                publicationName = publication,
                issueTitle = title,
                issueNumber = issueNumber,
                pages = new List<MagazinePageContent>(pages)
            };
        }

        private static MagazinePageContent Page(
            MagazinePageLayout layout, LocalizedText kicker, LocalizedText headline, LocalizedText deck,
            LocalizedText left, LocalizedText right, LocalizedText quote, LocalizedText sidebarTitle, LocalizedText sidebarBody,
            string relatedPlayerId, int illustrationIndex = -1, int illustrationIndex2 = -1)
        {
            return new MagazinePageContent
            {
                layout = layout,
                kicker = kicker,
                headline = headline,
                deck = deck,
                bodyLeft = left,
                bodyRight = right,
                pullQuote = quote,
                sidebarTitle = sidebarTitle,
                sidebarBody = sidebarBody,
                relatedPlayerId = relatedPlayerId,
                illustrationIndex = illustrationIndex,
                illustrationIndex2 = illustrationIndex2
            };
        }

        private static LocalizedText L(string zh, string en)
        {
            return new LocalizedText
            {
                chineseSimplified = zh ?? string.Empty,
                english = en ?? string.Empty
            };
        }
    }
}
